export let suggestData = [
    { "the-type":'field' ,checkName: 'bob', checkKey: '111111', value: {"name":"bob","age":"12","otherParams":"..."} },
    { "the-type":'field' ,checkName: 'alice', checkKey: '222222', value: {"name":"alice","age":"25","otherParams":"..."} },
    { "the-type":'field' ,checkName: 'charlie', checkKey: '333333', value: {"name":"charlie","age":"35","otherParams":"..."} },
    { "the-type":'field' ,checkName: 'david', checkKey: '444444', value: {"name":"david","age":"40","otherParams":"..."} },
    { "the-type":'field' ,checkName: 'eve', checkKey: '555555', value: {"name":"eve","age":"45","otherParams":"..."} },
    { "the-type":'field' ,checkName: 'eve1', checkKey: '1555555', value: {"name":"eve","age":"45","otherParams":"..."} },
    { "the-type":'field' ,checkName: 'eve2', checkKey: '2555555', value: {"name":"eve","age":"45","otherParams":"..."} },
    { "the-type":'field' ,checkName: 'eve3', checkKey: '3555555', value: {"name":"eve","age":"45","otherParams":"..."} },
    { "the-type":'field' ,checkName: 'eve4', checkKey: '4555555', value: {"name":"eve","age":"45","otherParams":"..."} },
    { "the-type":'field' ,checkName: 'eve4', checkKey: '4555555', value: {"name":"eve","age":"45","otherParams":"..."} },
    { "the-type":'field' ,checkName: 'func1(arg1,arg2)', checkKey: '1001', value: {"name":"func1","remark":"说明：这是函数说明","otherParams":"..."} },
    { "the-type":'method' ,checkName: 'func2(arg1,arg2)', checkKey: '1002', value: {"name":"func2","remark":"说明：这是函数说明","otherParams":"..."} },
    { "the-type":'method' ,checkName: 'func3(arg1,arg2)', checkKey: '1003', value: {"name":"func3","remark":"说明：这是函数说明","otherParams":"..."} },
    { "the-type":'method' ,checkName: 'func4(arg1,arg2)', checkKey: '1004', value: {"name":"func4","remark":"说明：这是函数说明","otherParams":"..."} },
    { "the-type":'method' ,checkName: 'func5(arg1,arg2)', checkKey: '1005', value: {"name":"func5","remark":"说明：这是函数说明","otherParams":"..."} },
    { "the-type":'method' ,checkName: 'func6(arg1,arg2)', checkKey: '1006', value: {"name":"func6","remark":"说明：这是函数说明","otherParams":"..."} },
    { "the-type":'method' ,checkName: 'func7(arg1,arg2)', checkKey: '1007', value: {"name":"func7","remark":"说明：这是函数说明","otherParams":"..."} },
    { "the-type":'method' ,checkName: 'func8(arg1,arg2)', checkKey: '1008', value: {"name":"func8","remark":"说明：这是函数说明","otherParams":"..."} },
    { "the-type":'method' ,checkName: 'func9(arg1,arg2)', checkKey: '1009', value: {"name":"func9","remark":"说明：这是函数说明","otherParams":"..."} },
    { "the-type":'method' ,checkName: 'func10(arg1,arg2)', checkKey: '10010', value: {"name":"func10","remark":"说明：这是函数说明","otherParams":"..."} },
];
