{
  "code": 200,
  "data": {
      "list": [
          {
              "commoditiesBoardId": 0,
              "id": 1,
              "name": "今日推荐",
              "imageUrl": "http://img1.lukou.com/static/p/fb/tab/1/20181211-151644.jpeg",
              "extraData": "{\"need_banner\":1, \"category_id\":13, \"need_grid\":1}",
              "flowBoardId": 89,
              "note": "小编精选，全场特惠 (ง •̀_•́)ง",
              "gridsBoardId": 3,
              "bannerBoardId": 2,
              "feedsBoardId": 0,
              "categoryId": 0
          },
          {
              "commoditiesBoardId": 157,
              "id": 2,
              "name": "女装",
              "imageUrl": "http://img1.lukou.com/static/p/fb/tab/2/20190220-155007.png",
              "extraData": "{\"category_id\":1, \"fe_category_id\":1689}",
              "flowBoardId": 75,
              "note": "",
              "gridsBoardId": 4,
              "bannerBoardId": 0,
              "feedsBoardId": 5,
              "categoryId": 1689
          },
          {
              "commoditiesBoardId": 158,
              "id": 5,
              "name": "男装",
              "imageUrl": "http://img1.lukou.com/static/p/fb/tab/5/20190220-154814.png",
              "extraData": "{\"category_id\":9, \"fe_category_id\":1699}",
              "flowBoardId": 78,
              "note": "",
              "gridsBoardId": 10,
              "bannerBoardId": 0,
              "feedsBoardId": 11,
              "categoryId": 1699
          },
          {
              "commoditiesBoardId": 205,
              "id": 4,
              "name": "配饰",
              "imageUrl": "http://img1.lukou.com/static/img/category/category_4.jpg",
              "extraData": "{\"category_id\":5, \"fe_category_id\":1727}",
              "flowBoardId": 77,
              "note": "",
              "gridsBoardId": 6,
              "bannerBoardId": 0,
              "feedsBoardId": 7,
              "categoryId": 1727
          },
          {
              "commoditiesBoardId": 0,
              "id": 13,
              "name": "女鞋",
              "imageUrl": "http://img1.lukou.com/static/p/fb/tab/13/20190411-171049.png",
              "extraData": "{\"category_id\":\"1710\"}",
              "flowBoardId": 79,
              "note": "",
              "gridsBoardId": 16,
              "bannerBoardId": 0,
              "feedsBoardId": 17,
              "categoryId": 1710
          },
          {
              "commoditiesBoardId": 167,
              "id": 19,
              "name": "男鞋",
              "imageUrl": "http://img1.lukou.com/static/p/fb/tab/19/20180713-163524.jpeg",
              "extraData": "{}",
              "flowBoardId": 258,
              "note": "",
              "gridsBoardId": 107,
              "bannerBoardId": 0,
              "feedsBoardId": 0,
              "categoryId": 1833
          },
          {
              "commoditiesBoardId": 0,
              "id": 10,
              "name": "零食",
              "imageUrl": "http://img1.lukou.com/static/img/category/category_12.jpg",
              "extraData": "{\"category_id\":6, \"fe_category_id\":1748}",
              "flowBoardId": 86,
              "note": "",
              "gridsBoardId": 30,
              "bannerBoardId": 0,
              "feedsBoardId": 31,
              "categoryId": 1748
          },
          {
              "commoditiesBoardId": 159,
              "id": 16,
              "name": "内衣袜子",
              "imageUrl": "http://img1.lukou.com/static/p/fb/tab/16/20181211-151820.jpeg",
              "extraData": "{\"category_id\":\"1770\"}",
              "flowBoardId": 84,
              "note": "",
              "gridsBoardId": 26,
              "bannerBoardId": 0,
              "feedsBoardId": 27,
              "categoryId": 1770
          },
          {
              "commoditiesBoardId": 165,
              "id": 24,
              "name": "母婴用品",
              "imageUrl": "http://img1.lukou.com/static/p/fb/tab/24/20180725-200843.png",
              "extraData": "{}",
              "flowBoardId": 0,
              "note": "",
              "gridsBoardId": 164,
              "bannerBoardId": 0,
              "feedsBoardId": 0,
              "categoryId": 1939
          },
          {
              "commoditiesBoardId": 202,
              "id": 14,
              "name": "箱包",
              "imageUrl": "http://img1.lukou.com/static/img/category/category_7.jpg",
              "extraData": "{\"category_id\":\"1719\"}",
              "flowBoardId": 80,
              "note": "",
              "gridsBoardId": 18,
              "bannerBoardId": 0,
              "feedsBoardId": 19,
              "categoryId": 1719
          },
          {
              "commoditiesBoardId": 0,
              "id": 12,
              "name": "数码家电",
              "imageUrl": "http://img1.lukou.com/static/img/category/category_10.jpg",
              "extraData": "{\"category_id\":\"1742\"}",
              "flowBoardId": 83,
              "note": "",
              "gridsBoardId": 24,
              "bannerBoardId": 0,
              "feedsBoardId": 25,
              "categoryId": 1742
          },
          {
              "commoditiesBoardId": 0,
              "id": 7,
              "name": "日用家居",
              "imageUrl": "http://img1.lukou.com/static/p/fb/tab/7/20181228-222551.png",
              "extraData": "{\"category_id\":4, \"fe_category_id\":1763}",
              "flowBoardId": 87,
              "note": "",
              "gridsBoardId": 32,
              "bannerBoardId": 0,
              "feedsBoardId": 33,
              "categoryId": 1763
          },
          {
              "commoditiesBoardId": 0,
              "id": 11,
              "name": "文体娱乐",
              "imageUrl": "http://img1.lukou.com/static/img/category/category_14.jpg",
              "extraData": "{\"category_id\":7, \"fe_category_id\":1776}",
              "flowBoardId": 88,
              "note": "",
              "gridsBoardId": 34,
              "bannerBoardId": 0,
              "feedsBoardId": 35,
              "categoryId": 1776
          }
      ]
  }
}